import { MigrationInterface, QueryRunner } from "typeorm";

export class Setup1710388486936 implements MigrationInterface {
    name = 'Setup1710388486936'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."log_app_id"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "team_member_userid_teamid_key"`);
        await queryRunner.query(`ALTER TABLE "team_apps" DROP CONSTRAINT "team_apps_teamid_appid_key"`);
        await queryRunner.query(`ALTER TABLE "metrics" RENAME COLUMN "appid" TO "appId"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "amount" double precision NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "plancode"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "plancode" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tiers" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tiers" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP CONSTRAINT "tiers_name_key"`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD CONSTRAINT "UQ_ef8721c02725f7720897bfc358b" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP COLUMN "generallyavailable"`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD "generallyavailable" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_member" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_member" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "logs" DROP CONSTRAINT "logs_app"`);
        await queryRunner.query(`ALTER TABLE "apps" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "apps" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "apps_token_key"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "apps" ADD "token" uuid NOT NULL`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "UQ_7d1818ae4cf21482433b999123a" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "team_apps" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "team_apps" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "name" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isadmin"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isadmin" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "githubid"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "githubid" character varying`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "level"`);
        await queryRunner.query(`DROP TYPE "public"."loglevel"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "level" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "ip"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "ip" character varying`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "saved"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "saved" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "apptoken"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "apptoken" uuid`);
        await queryRunner.query(`ALTER TABLE "metrics" ALTER COLUMN "createdat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "metrics" ALTER COLUMN "updatedat" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "metrics" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "metrics" ADD "level" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "UQ_0c989f253885942d5f349afbffd" UNIQUE ("userid", "teamid")`);
        await queryRunner.query(`ALTER TABLE "team_apps" ADD CONSTRAINT "UQ_347f3badddccd62c4b84c2186fa" UNIQUE ("teamid", "appid")`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD CONSTRAINT "FK_8e2a633f891b89c41396e113458" FOREIGN KEY ("planid") REFERENCES "payment_plans"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_68674703343ea878ef091faa149" FOREIGN KEY ("userid") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_85add16229af52b1bc7fe8832c6" FOREIGN KEY ("tierid") REFERENCES "tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_1933edcd1a8648dda3d48bbe2e3" FOREIGN KEY ("userid") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "FK_35978b527358a915ef7a333f631" FOREIGN KEY ("teamid") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "FK_d91aab7310ca647e2bbc3c58462" FOREIGN KEY ("userid") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_apps" ADD CONSTRAINT "FK_72baa12fefa81986c9aa2a12c87" FOREIGN KEY ("teamid") REFERENCES "teams"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_apps" ADD CONSTRAINT "FK_3b1b45e34e2d40bfda48c9f3d73" FOREIGN KEY ("appid") REFERENCES "apps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "teams" ADD CONSTRAINT "FK_c58d98addf3fbbcb3201fe7ba98" FOREIGN KEY ("ownerid") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "logs" ADD CONSTRAINT "logs_app" FOREIGN KEY ("apptoken") REFERENCES "apps"("token") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "metrics" ADD CONSTRAINT "FK_96312cf2649df2778165c00979a" FOREIGN KEY ("appId") REFERENCES "apps"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`CREATE TABLE "query-result-cache" ("id" SERIAL NOT NULL, "identifier" character varying, "time" bigint NOT NULL, "duration" integer NOT NULL, "query" text NOT NULL, "result" text NOT NULL, CONSTRAINT "PK_6a98f758d8bfd010e7e10ffd3d3" PRIMARY KEY ("id"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "query-result-cache"`);
        await queryRunner.query(`ALTER TABLE "metrics" DROP CONSTRAINT "FK_96312cf2649df2778165c00979a"`);
        await queryRunner.query(`ALTER TABLE "logs" DROP CONSTRAINT "logs_app"`);
        await queryRunner.query(`ALTER TABLE "teams" DROP CONSTRAINT "FK_c58d98addf3fbbcb3201fe7ba98"`);
        await queryRunner.query(`ALTER TABLE "team_apps" DROP CONSTRAINT "FK_3b1b45e34e2d40bfda48c9f3d73"`);
        await queryRunner.query(`ALTER TABLE "team_apps" DROP CONSTRAINT "FK_72baa12fefa81986c9aa2a12c87"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "FK_d91aab7310ca647e2bbc3c58462"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_35978b527358a915ef7a333f631"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "FK_1933edcd1a8648dda3d48bbe2e3"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_85add16229af52b1bc7fe8832c6"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_68674703343ea878ef091faa149"`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP CONSTRAINT "FK_8e2a633f891b89c41396e113458"`);
        await queryRunner.query(`ALTER TABLE "team_apps" DROP CONSTRAINT "UQ_347f3badddccd62c4b84c2186fa"`);
        await queryRunner.query(`ALTER TABLE "team_member" DROP CONSTRAINT "UQ_0c989f253885942d5f349afbffd"`);
        await queryRunner.query(`ALTER TABLE "metrics" DROP COLUMN "level"`);
        await queryRunner.query(`ALTER TABLE "metrics" ADD "level" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "metrics" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "metrics" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "apptoken"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "apptoken" character varying(36)`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "saved"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "saved" bit NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "ip"`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "ip" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "logs" DROP COLUMN "level"`);
        await queryRunner.query(`CREATE TYPE "public"."loglevel" AS ENUM('info', 'error', 'warn', 'debug', 'critical', 'fatal')`);
        await queryRunner.query(`ALTER TABLE "logs" ADD "level" "public"."loglevel" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "logs" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "githubid"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "githubid" character varying(255)`);
        await queryRunner.query(`ALTER TABLE "users" DROP COLUMN "isadmin"`);
        await queryRunner.query(`ALTER TABLE "users" ADD "isadmin" bit NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "teams" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "teams" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "teams" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "team_apps" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "team_apps" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "apps" DROP CONSTRAINT "UQ_7d1818ae4cf21482433b999123a"`);
        await queryRunner.query(`ALTER TABLE "apps" DROP COLUMN "token"`);
        await queryRunner.query(`ALTER TABLE "apps" ADD "token" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "apps" ADD CONSTRAINT "apps_token_key" UNIQUE ("token")`);
        await queryRunner.query(`ALTER TABLE "apps" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "apps" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "logs" ADD CONSTRAINT "logs_app" FOREIGN KEY ("apptoken") REFERENCES "apps"("token") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "team_member" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "team_member" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "accounts" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP COLUMN "generallyavailable"`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD "generallyavailable" bit NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP CONSTRAINT "UQ_ef8721c02725f7720897bfc358b"`);
        await queryRunner.query(`ALTER TABLE "tiers" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tiers" ADD CONSTRAINT "tiers_name_key" UNIQUE ("name")`);
        await queryRunner.query(`ALTER TABLE "tiers" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "tiers" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "plancode"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "plancode" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "amount"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "amount" real NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_plans" DROP COLUMN "name"`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ADD "name" character varying(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ALTER COLUMN "updatedat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "payment_plans" ALTER COLUMN "createdat" SET DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE "metrics" RENAME COLUMN "appId" TO "appid"`);
        await queryRunner.query(`ALTER TABLE "team_apps" ADD CONSTRAINT "team_apps_teamid_appid_key" UNIQUE ("teamid", "appid")`);
        await queryRunner.query(`ALTER TABLE "team_member" ADD CONSTRAINT "team_member_userid_teamid_key" UNIQUE ("userid", "teamid")`);
        await queryRunner.query(`CREATE INDEX "log_app_id" ON "logs" ("apptoken") `);
    }

}
